public enum DOC_TYPE
{
    INFO_PROTOBUF = 10,

    PDF_OGRINAL = 20,
    PDF_COMPRESS = 21,

    IMG_OGRINAL = 30,
    IMG_NO_BORDER_PAGE = 31,
    IMG_LINES = 32,
    IMG_OGRINAL_SIZE = 33,

    TEXT_OGRINAL = 80,
    TEXT_COMPRESS = 81,

    HTML_OGRINAL = 90,
    HTML_COMPRESS = 91,
}